version: '3.4'

services:
  frontend:
    build: frontend
    restart: always
    depends_on:
      - nginx
  backend:
    build: backend
    restart: always
    depends_on:
      - nginx
    env_file:
      - backend/.env
    environment:
      PORT: 9000
      LOG_LEVEL: "debug"
      ALLOWED_ORIGINS: "https://afk-cookbook.fkor.us"
      OAUTH_GOOGLE_CLIENT_ID: "325396365340-a0ufpksrnsmigrpko21ah2to0n3p6uv9.apps.googleusercontent.com"
  nginx:
    build: nginx
    restart: always
    ports:
      - "7777:80"
